services:
  package-registry:
    image: docker.elastic.co/package-registry/package-registry:latest
    ports:
      - "8080:8080"
      - "4443:4443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      start_period: 300s
      interval: 5s
    volumes:
      - ${SEARCH_INDEX_PATH}:/testdata/search-index-all.json
    environment:
      - STORAGE_EMULATOR_HOST=localhost:4443
      - EPR_EMULATOR_INDEX_PATH=/testdata/search-index-all.json
      - EPR_STORAGE_INDEXER_BUCKET_INTERNAL=gs://fake-package-storage-internal
      - EPR_FEATURE_STORAGE_INDEXER=true
      - EPR_DISABLE_PACKAGE_VALIDATION=true
      - EPR_ADDRESS=0.0.0.0:8080
  package-registry_is_ready:
    image: tianon/true:multiarch
    depends_on:
      package-registry:
        condition: service_healthy


