title: Prometheus remote_write metrics
release: beta
type: metrics
streams:
- input: prometheus/metrics
  title: Prometheus remote_write metrics
  description: Collect Prometheus remote_write metrics
