format_version: 1.0.0
name: traefik
title: traefik
version: 0.0.1
license: basic
description: traefik Integration
type: integration
categories:
- logs
- metrics
release: ga
requirement:
  kibana:
    versions: '>=7.3.0 <8.0.0'
  elasticsearch:
    versions: '>7.0.1'
screenshots:
- src: /img/kibana-traefik.png
  title: kibana traefik
  size: 1409x1254
  type: image/png
icons:
- src: /img/traefik.svg
  title: traefik
  size: 340x456
  type: image/svg+xml
datasources:
- name: traefik
  title: traefik logs and metrics
  description: Collect logs and metrics from traefik instances
  inputs:
  - type: logs
    description: Collecting traefik logs
  - type: traefik/metrics
    description: Collecting traefik metrics
