title: Prometheus typed metrics collector metrics
release: ga
type: metrics
streams:
- input: prometheus/metrics
  title: Prometheus typed metrics collector metrics
  description: Collect Prometheus typed metrics collector metrics
